name: Docker CI

on:
  workflow_call:
    inputs:
      aws_region:
        type: string
        required: false
        default: us-east-1
      retag_from:
        type: string
        required: true
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
    outputs:
      image_tag:
        description: "Image tag version"
        value: ${{ jobs.retag.outputs.image_tag }}

jobs:
  retag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.retag-image.outputs.image_tag }}
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Retag and push image to Amazon ECR
      id: retag-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        COMMIT_SHA: ${{ github.sha }}
      run: |
        ECR_REPOSITORY=${GITHUB_REPOSITORY#*/}
        SHORT_COMMIT_SHA=${COMMIT_SHA:0:7}
        
        SOURCE_IMAGE_TAG=${{ inputs.retag_from }}-${SHORT_COMMIT_SHA}
        IMAGE_TAG=${{ github.ref_name }}
        
        docker pull ${ECR_REGISTRY}/${ECR_REPOSITORY}:${SOURCE_IMAGE_TAG}
        docker tag ${ECR_REGISTRY}/${ECR_REPOSITORY}:${SOURCE_IMAGE_TAG} ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
        docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}

        echo "::set-output name=image_tag::${IMAGE_TAG}"
