name: Kubernetes CD

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      environment:
        type: string
        required: true
      aws_region:
        type: string
        required: false
        default: us-east-1
      aws_role_arn:
        type: string
        required: true
      eks_cluster_name:
        type: string
        required: true
      gcp_project_id:
        type: string
        required: true
      gcp_zone:
        type: string
        required: false
        default: us-east1-d
      gke_cluster_name:
        type: string
        required: true
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      gcp_service_account_key:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v2
    - uses: azure/setup-helm@v1
      id: install
      with:
        version: v3.8.0
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}
    - uses: google-github-actions/auth@v0
      with:
        project_id: ${{ inputs.gcp_project_id }}
        credentials_json: ${{ secrets.gcp_service_account_key }}
    - uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ inputs.gke_cluster_name }}
        location: ${{ inputs.gcp_zone }}
    - name: Helm upgrade
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        RELEASE_NAME=${GITHUB_REPOSITORY#*/}
        CHART_PATH=charts/${RELEASE_NAME}

        case ${{ inputs.environment }} in
          dev)
            NAMESPACE=${RELEASE_NAME}-dev
            VALUES=${CHART_PATH}/env/values.dev.yaml
          ;;
          stage)
            NAMESPACE=${RELEASE_NAME}-stage
            VALUES=${CHART_PATH}/env/values.stage.yaml
          ;;
          prod)
            NAMESPACE=${RELEASE_NAME}
            VALUES=${CHART_PATH}/env/values.prod.yaml
          ;;
        esac
        
        # Deploy GKE
        helm upgrade ${RELEASE_NAME} ${CHART_PATH} --create-namespace --namespace ${NAMESPACE} --install --values ${VALUES} --set provider=gcp --set image.tag=${{ inputs.version }}
        
        # Deploy EKS
        aws eks update-kubeconfig --region ${{ inputs.aws_region }} --name ${{ inputs.eks_cluster_name }} --role-arn ${{ inputs.aws_role_arn }}
        helm upgrade ${RELEASE_NAME} ${CHART_PATH} --create-namespace --namespace ${NAMESPACE} --install --values ${VALUES} --set provider=aws --set image.tag=${{ inputs.version }}
