name: Kubernetes Deployment

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      image_tags:
        type: string
        required: true
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      gcp_service_account_key:
        required: true

env:
  ENV: ${{ inputs.env }}
  AWS_ACCOUNT_ID: 616462286528
  AWS_REGION: us-east-1
  ROLE_ARN_SUFFIX: AmazonEKSAdmin
  EKS_CLUSTERS: ([dev]=k8s-sdlc-34750c77 [stage]=k8s-sdlc-34750c77 [prod]=k8s-prod-addb9393)
  GCP_PROJECT_ID: plataforma-relacionamento
  GCP_ZONE: us-east1-d
  GKE_CLUSTERS: ([dev]=k8s-sdlc-37b6164a [stage]=k8s-sdlc-37b6164a [prod]=k8s-prod-c4f54ce6)

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: quay.io/roboll/helmfile:v0.143.1
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        id: set_env
        run: |
          declare -A EKS_CLUSTERS GKE_CLUSTERS
          
          IMAGE_TAGS=(${{ inputs.image_tags }})

          echo "APP_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "EKS_CLUSTER_NAME=${EKS_CLUSTERS[$ENV]}" >> $GITHUB_ENV
          echo "GKE_CLUSTER_NAME=${GKE_CLUSTERS[$ENV]}" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=${IMAGE_TAGS[0]%:*}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${IMAGE_TAGS[0]#*:}" >> $GITHUB_ENV

      - uses: google-github-actions/auth@v0
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.gcp_service_account_key }}

      - uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GCP_ZONE }}
          credentials: ${{ secrets.gcp_service_account_key }}

      - name: GCP Helm upgrade
        run: |
          helmfile -f charts/helmfile.yaml -e gcp-${ENV} apply

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ env.AWS_REGION }}

      - name: AWS Helm upgrade 
        run: |
          aws eks update-kubeconfig --region ${AWS_REGION} --name ${EKS_CLUSTER_NAME} --role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/${EKS_CLUSTER_NAME}-${ROLE_ARN_SUFFIX}
          helmfile -f charts/helmfile.yaml -e aws-${ENV} apply