name: Kubernetes CD

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      eks-location:
        type: string
        required: false
        default: us-east-1
      eks-cluster-name:
        type: string
        required: true
      role-arn:
        type: string
        required: true
      gke-project-id:
        type: string
        required: true
      gke-cluster-name:
        type: string
        required: true
      gke-location:
        type: string
        required: false
        default: us-east1-d
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      gke-sa-key:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v2
    - uses: azure/setup-helm@v1
      id: install
      with:
        version: v3.8.0
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws-access-key-id }}
        aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
        aws-region: ${{ inputs.eks-location }}
    - uses: google-github-actions/auth@v0
      with:
        project_id: ${{ inputs.gke-project-id }}
        credentials_json: ${{ secrets.gke-sa-key }}
    - uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ inputs.gke-cluster-name }}
        location: ${{ inputs.gke-location }}
    - name: Helm upgrade
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        COMMIT_SHA: ${{ github.sha }}
      run: |
        RELEASE_NAME=${GITHUB_REPOSITORY#*/}
        SHORT_COMMIT_SHA=${COMMIT_SHA:0:7}

        [[ ${{ github.ref_type }} == 'branch' ]] && IMAGE_TAG=${{ github.ref_name }}-${SHORT_COMMIT_SHA}
        [[ ${{ github.ref_type }} == 'tag' ]] && IMAGE_TAG=${{ github.ref_name }}
        
        CHART_PATH=charts/${RELEASE_NAME}

        case ${{ inputs.environment }} in
          dev)
            NAMESPACE=${RELEASE_NAME}-dev
            VALUES=${CHART_PATH}/env/values.dev.yaml
          ;;
          stage)
            NAMESPACE=${RELEASE_NAME}-stage
            VALUES=${CHART_PATH}/env/values.stage.yaml
          ;;
          prod)
            NAMESPACE=${RELEASE_NAME}
            VALUES=${CHART_PATH}/env/values.prod.yaml
          ;;
        esac
        
        # Deploy GKE
        helm upgrade ${RELEASE_NAME} ${CHART_PATH} --create-namespace --namespace ${NAMESPACE} --install --values ${VALUES} --set provider=gcp --set image.tag=${IMAGE_TAG}
        
        # Deploy EKS
        aws eks update-kubeconfig --region ${{ inputs.eks-location }} --name ${{ inputs.eks-cluster-name }} --role-arn ${{ inputs.role-arn }}
        helm upgrade ${RELEASE_NAME} ${CHART_PATH} --create-namespace --namespace ${NAMESPACE} --install --values ${VALUES} --set provider=aws --set image.tag=${IMAGE_TAG}
