name: Node.js CI

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: false
        default: '14'
      skip-test:
        type: boolean
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          node_modules
          dist
          .next
          out
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Build
      run: npm run build --if-present

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          node_modules
          dist
          .next
          out
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Lint
      run: npm run lint
    - name: Test
      if: ${{ ! inputs.skip-test }}
      run: npm test
